[package]
edition.workspace = true
license.workspace = true
name = "tx_macro"
publish.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
