[workspace.package]
edition = "2021"
license = "Apache-2.0"
name = "fitness-ledger"
publish = false
version = "0.1.0"

[workspace]
members = ["bins", "mini-app", "storage"]
resolver = "2"

[workspace.dependencies]
mini-app = {path = "mini-app"}
storage = {path = "storage"}

#libs 
dotenv = "0.15.0"
