version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - "./data:/data/db"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 127.0.0.1:8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
  #     ME_CONFIG_MONGODB_URL: mongodb://root:$MONGO_ROOT_PASSWORD@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false    
  backend:
    build: .
    restart: always
    environment:
      MONGO_URL: $MONGO_URL
      TG_TOKEN: $TG_TOKEN
      RUST_LOG: $RUST_LOG
