services:
  mongo:
    build: mongodb
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      HOST: $HOST
    volumes:
      - "./data:/data/db"
  backend:
    build: .
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    environment:
      MONGO_URL: $MONGO_URL
      TG_TOKEN: $TG_TOKEN
      RUST_LOG: $RUST_LOG
      MINI_APP_KEY: $MINI_APP_KEY
      APP_URL: $APP_URL
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/ssl/certs
        - ./bot-static:/bot-static/static
      depends_on:
        - backend
