services:
  mongo:
    build: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - "./data:/data/db"
  mongosetup:
    image: mongo
    depends_on:
      - mongo
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 20 && ./init.sh"] 
  # backend:
  #   build: .
  #   restart: always
  #   environment:
  #     MONGO_URL: $MONGO_URL
  #     TG_TOKEN: $TG_TOKEN
  #     RUST_LOG: $RUST_LOG

