[package]
name = "ai"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
eyre.workspace = true
log.workspace = true
