[package]
name = "storage"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
eyre.workspace = true
mongodb.workspace = true
serde.workspace = true
serde_with.workspace = true