[package]
name = "bot"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
ledger.workspace = true
eyre.workspace = true
teloxide.workspace = true