[package]
name = "model"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
mongodb.workspace = true
serde.workspace = true
eyre.workspace = true
chrono.workspace = true
bson.workspace = true
strum.workspace = true
