[package]
name = "model"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
mongodb.workspace = true
log.workspace = true
eyre.workspace = true
