[package]
name = "graph"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
plotly.workspace = true

ndarray = "0.16"
rand = "0.8"
rand_distr = "0.4"